#!/usr/bin/env bash
# My Naturewatch Camera Builder
# Builds NaturewatchCameraServer and dependencies
# Written by Mike Vanis
# GPL V3
########


# Source error handling, leave this in place
set -x
set -e

source /common.sh
install_cleanup_trap

unpack /filesystem/home/pi /home/"${BASE_USER}" "${BASE_USER}"
unpack /filesystem/home/root /root root
unpack /filesystem/boot /boot
unpack /filesystem/usr/local/src /usr/local/src

pushd /NaturewatchCameraServer
source /install.sh /usr/local/src
popd

unpack /filesystem/home/pi /home/"${BASE_USER}" "${BASE_USER}"
# Unpack root at the end, so files are modified before
unpack /filesystem/root /
